### ISSUE TITLE
Understand how to get Perfmon data from Powershell

### ISSUE THREAD

**Issue by mathewlk** [Snap-for-Windows/snap-plugin-collector-perfmon#5]

**Comment by mathewlk** [comment]
Basics on using the Performance Monitor tool in Windows (counters objects, data collector sets, loading a data log): https://www.youtube.com/watch?v=00yyCMJWIpA

**Comment by mathewlk** [comment]
Basic overview of using PowerShell commands to gather counter data (and how to get data from remote computers): https://www.simple-talk.com/sysadmin/powershell/powershell-day-to-day-admin-tasks-monitoring-performance/ 

Apparently, we can export data gathered with Powershell into .blg (which can be viewed through the Performance Monitor application), .csv, or .tsv formats.

**Comment by mathewlk** [comment]
Here is the script we will definitely want to run in our GO code. It gets specific counters (which we can specify) from remote servers and exports the data to a .csv file: https://gallery.technet.microsoft.com/scriptcenter/PowerShell-Perfmon-0f013da8

**Comment by jessemillar** [comment]
LGTM

**Comment by jessemillar** [comment]
Do we know what the licensing is on that PowerShell Perfmon script from Microsoft? Can we just include that in our repo?

**Comment by mathewlk** [comment]
After reading the Terms of Use on the page I think we can use it as long as it's not for profit (remains open source). But it's long and used a lot of confusing jargon so I'm not 100% on that. It is available for download though...maybe we can talk to Greg Lunt about it?

**Comment by mathewlk** [comment]
According to https://github.com/intelsdi-x/snap/blob/master/docs/PLUGIN_AUTHORING.md, we should figure out which metrics to start collecting. To keep it simple, I think we should start with Committed Memory Bytes in use, Available Memory MBytes, and Total Processor Time. I ran the powershell script and these were the ones which actually had data. Until we get the test environment setup these should be fairly simple to test.

-

**Comment by jessemillar** [comment]
Sounds good to me.
